### ISSUE TITLE
OpenRazer update breaks Polychromatic

### ISSUE THREAD

**Issue by PDXsailor** [polychromatic/polychromatic#146]
Yesterday I took an  OpenRazer update through the Software Update Manager (using PPA as source) in Mint 18.3. After reboot Polychromatic fails. Attached is error screen.
![openrazerfail](https://user-images.githubusercontent.com/34016900/38209856-7618fe2e-366a-11e8-9caf-b495b476b63a.png)

**Comment by PDXsailor** [comment]
Update was to OpenRazer 2.3.0.

**Comment by lah7** [comment]
Seems strange... it looks like a Razer Mamba 2012 (`153:0224`, a mouse) is trying to find out which keyboard layout it has. :confused: 

Which Razer devices do you have plugged in to your system?

Please post the output of the command in full so I can get a better idea of what's happening:

    polychromatic-controller -v

**Comment by lah7** [comment]
Having looked at the `stable` branch of code, "patching" it with this command should address the issue:

    sudo sed -i 's#get_keyboard_layout()#"gb"#g' /usr/bin/polychromatic-controller

**Comment by FinalMiner** [comment]
Same issue as above. In my case I am actually using a keyboard. I confirmed that the file "kbd_layout" did not exist, but the directory path did. Restarting daemon got same error.

Here's my output from "polychromatic-controller -v".

> ERROR: Exception: org.freedesktop.DBus.Python.FileNotFoundError: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 707, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/lib/python3/dist-packages/openrazer_daemon/dbus_services/dbus_methods/all.py", line 85, in get_keyboard_layout
    with open(driver_path, 'r') as driver_file:
FileNotFoundError: [Errno 2] No such file or directory: '/sys/devices/pci0000:00/0000:00:14.0/usb1/1-10/1-10:1.2/0003:1532:021E.0003/kbd_layout'
ERROR: Could not connect to the Daemon Device Manager!

**Comment by PDXsailor** [comment]
I am using a 2017 Kaby Lake Razer Blade, no external peripherals attached. It is not listed in OpenRazer's list of supported devices, but when I sent in the required info for requesting support I was told that it was covered and my ticket was closed. I guess that the ID is the same as the 2016 Skylake Razer Blade. Maybe that is the source of difficulties.

The patch did not work.

First is verbose output, then error from patched run (after a restart).
![polyverbose](https://user-images.githubusercontent.com/34016900/38226229-52b7d610-36ad-11e8-9c53-9a20df281540.png)
![newpolycontroller](https://user-images.githubusercontent.com/34016900/38226239-6228d158-36ad-11e8-88da-ab1a75250e91.png)

**Comment by z3ntu** [comment]
@PDXsailor Can you run `grep "kbd_layout" /usr/src/openrazer-driver-1.0.0/driver/razerkbd_driver.c` ?

**Comment by PDXsailor** [comment]
![grep](https://user-images.githubusercontent.com/34016900/38262234-7613afa2-3721-11e8-9a02-3615b6cc97e4.png)

**Comment by z3ntu** [comment]
Can you post the output of `ls -al /sys/bus/hid/drivers/razerkbd/0*/` ?

**Comment by PDXsailor** [comment]
greg@greg-Blade ~ $ ls -al /sys/bus/hid/drivers/razerkbd/0*/
/sys/bus/hid/drivers/razerkbd/0003:1532:0224.0002/:
total 0
drwxr-xr-x 5 root plugdev    0 Apr  2 23:09 .
drwxr-xr-x 5 root root       0 Apr  2 16:09 ..
-r--r--r-- 1 root plugdev 4096 Apr  2 23:09 country
lrwxrwxrwx 1 root plugdev    0 Apr  2 23:09 driver -> ../../../../../../../bus/hid/drivers/razerkbd
drwxr-xr-x 3 root plugdev    0 Apr  2 23:09 hidraw
drwxr-xr-x 3 root plugdev    0 Apr  2 23:09 input
-rw-rw---- 1 root plugdev 4096 Apr  2 23:09 key_alt_f4
-rw-rw---- 1 root plugdev 4096 Apr  2 23:09 key_alt_tab
-rw-rw---- 1 root plugdev 4096 Apr  2 23:09 key_super
-r--r--r-- 1 root plugdev 4096 Apr  2 23:09 modalias
drwxr-xr-x 2 root plugdev    0 Apr  2 23:09 power
-r--r--r-- 1 root plugdev 4096 Apr  2 23:09 report_descriptor
lrwxrwxrwx 1 root plugdev    0 Apr  2 23:09 subsystem -> ../../../../../../../bus/hid
-rw-r--r-- 1 root plugdev 4096 Apr  2 23:09 uevent

/sys/bus/hid/drivers/razerkbd/0003:1532:0224.0003/:
total 0
drwxr-xr-x 5 root plugdev    0 Apr  2 23:09 .
drwxr-xr-x 5 root root       0 Apr  2 16:09 ..
-r--r--r-- 1 root plugdev 4096 Apr  2 23:09 country
lrwxrwxrwx 1 root plugdev    0 Apr  2 23:09 driver -> ../../../../../../../bus/hid/drivers/razerkbd
drwxr-xr-x 3 root plugdev    0 Apr  2 23:09 hidraw
drwxr-xr-x 3 root plugdev    0 Apr  2 23:09 input
-rw-rw---- 1 root plugdev 4096 Apr  2 23:09 key_alt_f4
-rw-rw---- 1 root plugdev 4096 Apr  2 23:09 key_alt_tab
-rw-rw---- 1 root plugdev 4096 Apr  2 23:09 key_super
-r--r--r-- 1 root plugdev 4096 Apr  2 23:09 modalias
drwxr-xr-x 2 root plugdev    0 Apr  2 23:09 power
-r--r--r-- 1 root plugdev 4096 Apr  2 23:09 report_descriptor
lrwxrwxrwx 1 root plugdev    0 Apr  2 23:09 subsystem -> ../../../../../../../bus/hid
-rw-r--r-- 1 root plugdev 4096 Apr  2 23:09 uevent

/sys/bus/hid/drivers/razerkbd/0003:1532:0224.0004/:
total 0
drwxr-xr-x 5 root plugdev    0 Apr  2 23:09 .
drwxr-xr-x 5 root root       0 Apr  2 16:09 ..
-r--r--r-- 1 root plugdev 4096 Apr  2 23:09 country
-rw-rw---- 1 root plugdev 4096 Apr  2 23:54 device_mode
-r--r----- 1 root plugdev 4096 Apr  2 23:09 device_serial
-r--r----- 1 root plugdev 4096 Apr  2 23:09 device_type
lrwxrwxrwx 1 root plugdev    0 Apr  2 23:09 driver -> ../../../../../../../bus/hid/drivers/razerkbd
-r--r----- 1 root plugdev 4096 Apr  2 23:09 firmware_version
--w--w---- 1 root plugdev 4096 Apr  2 23:09 fn_toggle
drwxr-xr-x 3 root plugdev    0 Apr  2 23:09 hidraw
drwxr-xr-x 3 root plugdev    0 Apr  2 23:09 input
-rw-rw---- 1 root plugdev 4096 Apr  2 23:09 matrix_brightness
--w--w---- 1 root plugdev 4096 Apr  2 23:09 matrix_custom_frame
--w--w---- 1 root plugdev 4096 Apr  2 23:09 matrix_effect_breath
--w--w---- 1 root plugdev 4096 Apr  2 23:09 matrix_effect_custom
--w--w---- 1 root plugdev 4096 Apr  2 23:09 matrix_effect_none
--w--w---- 1 root plugdev 4096 Apr  2 23:09 matrix_effect_reactive
--w--w---- 1 root plugdev 4096 Apr  2 23:09 matrix_effect_spectrum
--w--w---- 1 root plugdev 4096 Apr  2 23:09 matrix_effect_starlight
--w--w---- 1 root plugdev 4096 Apr  2 23:09 matrix_effect_static
--w--w---- 1 root plugdev 4096 Apr  2 23:09 matrix_effect_wave
-r--r--r-- 1 root plugdev 4096 Apr  2 23:09 modalias
drwxr-xr-x 2 root plugdev    0 Apr  2 23:09 power
-r--r--r-- 1 root plugdev 4096 Apr  2 23:09 report_descriptor
lrwxrwxrwx 1 root plugdev    0 Apr  2 23:09 subsystem -> ../../../../../../../bus/hid
-rw-rw---- 1 root plugdev 4096 Apr  2 23:09 test
-rw-r--r-- 1 root plugdev 4096 Apr  2 23:09 uevent
-r--r----- 1 root plugdev 4096 Apr  2 23:09 version
greg@greg-Blade ~ $

**Comment by TheShed412** [comment]
I have the 2016 Skylake Razer Blade Stealth and I am getting the same error.

Screenfetch:

```
 MMMMMMMMMMMMMMMMMMMMMMMMMmds+.        OS: Mint 18.2 sonya
 MMm----::-://////////////oymNMd+`     Kernel: x86_64 Linux 4.10.0-041000-generic
 MMd      /++                -sNMd:    Uptime: 26m
 MMNso/`  dMM    `.::-. .-::.` .hMN:   Packages: 2973
 ddddMMh  dMM   :hNMNMNhNMNMNh: `NMm   Shell: zsh 5.1.1
     NMm  dMM  .NMN/-+MMM+-/NMN` dMM   Resolution: 2560x1440
     NMm  dMM  -MMm  `MMM   dMM. dMM   DE: Cinnamon 3.4.6
     NMm  dMM  -MMm  `MMM   dMM. dMM   WM: Muffin
     NMm  dMM  .mmd  `mmm   yMM. dMM   WM Theme: Vivaldi (Numix Daily)
     NMm  dMM`  ..`   ...   ydm. dMM   GTK Theme: Mint-Y-Dark [GTK2/3]
     hMM- +MMd/-------...-:sdds  dMM   Icon Theme: Numix-Circle
     -NMm- :hNMNNNmdddddddddy/`  dMM   Font: Noto Sans 9
      -dMNs-``-::::-------.``    dMM   CPU: Intel Core i5-7200U CPU @ 3.1GHz
       `/dMNmy+/:-------------:/yMMM   GPU: Mesa DRI Intel(R) HD Graphics 620 (Kaby Lake GT2) 
          ./ydNMMMMMMMMMMMMMMMMMMMMM   RAM: 1848MiB / 7620MiB
             \.MMMMMMMMMMMMMMMMMMM    
```
                       
and output for `ls -al /sys/bus/hid/drivers/razerkbd/0*/`           
```
/sys/bus/hid/drivers/razerkbd/0003:1532:0220.0001/:
total 0
drwxr-xr-x 5 root plugdev    0 Apr  3 17:59 .
drwxr-xr-x 5 root root       0 Apr  3 17:59 ..
-r--r--r-- 1 root plugdev 4096 Apr  3 17:59 country
lrwxrwxrwx 1 root plugdev    0 Apr  3 17:59 driver -> ../../../../../../../bus/hid/drivers/razerkbd
drwxr-xr-x 3 root plugdev    0 Apr  3 17:59 hidraw
drwxr-xr-x 3 root plugdev    0 Apr  3 17:59 input
-rw-rw---- 1 root plugdev 4096 Apr  3 17:59 key_alt_f4
-rw-rw---- 1 root plugdev 4096 Apr  3 17:59 key_alt_tab
-rw-rw---- 1 root plugdev 4096 Apr  3 17:59 key_super
-r--r--r-- 1 root plugdev 4096 Apr  3 17:59 modalias
drwxr-xr-x 2 root plugdev    0 Apr  3 17:59 power
-r--r--r-- 1 root plugdev 4096 Apr  3 17:59 report_descriptor
lrwxrwxrwx 1 root plugdev    0 Apr  3 17:59 subsystem -> ../../../../../../../bus/hid
-rw-r--r-- 1 root plugdev 4096 Apr  3 17:59 uevent

/sys/bus/hid/drivers/razerkbd/0003:1532:0220.0002/:
total 0
drwxr-xr-x 5 root plugdev    0 Apr  3 17:59 .
drwxr-xr-x 5 root root       0 Apr  3 17:59 ..
-r--r--r-- 1 root plugdev 4096 Apr  3 17:59 country
lrwxrwxrwx 1 root plugdev    0 Apr  3 17:59 driver -> ../../../../../../../bus/hid/drivers/razerkbd
drwxr-xr-x 3 root plugdev    0 Apr  3 17:59 hidraw
drwxr-xr-x 3 root plugdev    0 Apr  3 17:59 input
-rw-rw---- 1 root plugdev 4096 Apr  3 17:59 key_alt_f4
-rw-rw---- 1 root plugdev 4096 Apr  3 17:59 key_alt_tab
-rw-rw---- 1 root plugdev 4096 Apr  3 17:59 key_super
-r--r--r-- 1 root plugdev 4096 Apr  3 17:59 modalias
drwxr-xr-x 2 root plugdev    0 Apr  3 17:59 power
-r--r--r-- 1 root plugdev 4096 Apr  3 17:59 report_descriptor
lrwxrwxrwx 1 root plugdev    0 Apr  3 17:59 subsystem -> ../../../../../../../bus/hid
-rw-r--r-- 1 root plugdev 4096 Apr  3 17:59 uevent

/sys/bus/hid/drivers/razerkbd/0003:1532:0220.0003/:
total 0
drwxr-xr-x 5 root plugdev    0 Apr  3 17:59 .
drwxr-xr-x 5 root root       0 Apr  3 17:59 ..
-r--r--r-- 1 root plugdev 4096 Apr  3 17:59 country
-rw-rw---- 1 root plugdev 4096 Apr  3 17:59 device_mode
-r--r----- 1 root plugdev 4096 Apr  3 17:59 device_serial
-r--r----- 1 root plugdev 4096 Apr  3 17:59 device_type
lrwxrwxrwx 1 root plugdev    0 Apr  3 17:59 driver -> ../../../../../../../bus/hid/drivers/razerkbd
-r--r----- 1 root plugdev 4096 Apr  3 17:59 firmware_version
--w--w---- 1 root plugdev 4096 Apr  3 17:59 fn_toggle
drwxr-xr-x 3 root plugdev    0 Apr  3 17:59 hidraw
drwxr-xr-x 3 root plugdev    0 Apr  3 17:59 input
-rw-rw---- 1 root plugdev 4096 Apr  3 17:59 logo_led_state
-rw-rw---- 1 root plugdev 4096 Apr  3 17:59 matrix_brightness
--w--w---- 1 root plugdev 4096 Apr  3 17:59 matrix_custom_frame
--w--w---- 1 root plugdev 4096 Apr  3 17:59 matrix_effect_breath
--w--w---- 1 root plugdev 4096 Apr  3 17:59 matrix_effect_custom
--w--w---- 1 root plugdev 4096 Apr  3 17:59 matrix_effect_none
--w--w---- 1 root plugdev 4096 Apr  3 17:59 matrix_effect_reactive
--w--w---- 1 root plugdev 4096 Apr  3 17:59 matrix_effect_spectrum
--w--w---- 1 root plugdev 4096 Apr  3 17:59 matrix_effect_static
--w--w---- 1 root plugdev 4096 Apr  3 17:59 matrix_effect_wave
-r--r--r-- 1 root plugdev 4096 Apr  3 17:59 modalias
drwxr-xr-x 2 root plugdev    0 Apr  3 17:59 power
-r--r--r-- 1 root plugdev 4096 Apr  3 17:59 report_descriptor
lrwxrwxrwx 1 root plugdev    0 Apr  3 17:59 subsystem -> ../../../../../../../bus/hid
-rw-rw---- 1 root plugdev 4096 Apr  3 17:59 test
-rw-r--r-- 1 root plugdev 4096 Apr  3 17:59 uevent
-r--r----- 1 root plugdev 4096 Apr  3 17:59 version
```

**Comment by evll** [comment]
I have Blackwidow 2016, the daemon is not responding either. The suggested patch did not help.

**Comment by z3ntu** [comment]
Do you all use Ubuntu (incl. derivatives)? Could you try reinstalling the openrazer-kernel-modules-dkms packages (I believe `apt-get install --reinstall openrazer-kernel-modules-dkms`)?

**Comment by evll** [comment]
Yes, I am using Ubuntu. And reinstalling the kernel modules helped. Thank you!

Actually, I was using a different package, so that one was removed and openrazer one was installed:
```
The following packages will be REMOVED:
  razer-kernel-modules-dkms
The following NEW packages will be installed:
  openrazer-kernel-modules-dkms
```

**Comment by z3ntu** [comment]
Interesting... We're using the new package since September 2017 already. Do you know if you ran the commands listed in the release notes of v2.0.0? https://github.com/openrazer/openrazer/releases/tag/v2.0.0

**Comment by TheShed412** [comment]
I'm currently using Mint and the reinstall didn't seem to help. I don't use the `ppa:terrz-utils/razer` ppa so according to that link I shouldn't have had to do anything.

**Comment by TheShed412** [comment]
```
╰─$ dpkg -l | grep razer
ii  openrazer-daemon                          2.3.0~ubuntu16.04.1                                     amd64        OpenRazer Device Daemon
ii  openrazer-doc                             2.3.0~ubuntu16.04.1                                     all          Documentation and examples for the OpenRazer Tools
ii  openrazer-kernel-modules-dkms             2.3.0~ubuntu16.04.1                                     amd64        OpenRazer Peripheral Drivers
ii  openrazer-meta                            2.3.0~ubuntu16.04.1                                     all          Metapackage for OpenRazer components
ii  python3-openrazer                         2.3.0~ubuntu16.04.1                                     all          OpenRazer Python Library
```

**Comment by PDXsailor** [comment]
I had installed with the current PPAs. I just used the Software Manager to remove and install PC and OR to no effect. dpkg had same results as above. It might be worth noting that Mint is based on Ubuntu 16.04, not the current 17.10. In May or June Mint 19.1 will be released based on Ubuntu 18.04.

**Comment by z3ntu** [comment]
Did you both try rebooting after reinstalling the package?

**Comment by TheShed412** [comment]
Yup. I tried reinstalling and rebooting twice.

**Comment by PDXsailor** [comment]
No, I can't restart at the moment. I've been doing a massive copy from my NAS to a USB drive through the Blade - it will finish in 6 hours. I could kill some processes if you like.

**Comment by TheShed412** [comment]
I was told to run this after install `sudo gpasswd -a <USERNAME> plugdev` but running that didn't change anything either

**Comment by TheShed412** [comment]
It prints `2.2.2`

**Comment by PDXsailor** [comment]
Same result: 2.2.2, and still there afterwards.
[polyterm.txt](https://github.com/polychromatic/polychromatic/files/1881727/polyterm.txt)

**Comment by z3ntu** [comment]
But `grep "#define VERSION" /usr/src/openrazer-driver-1.0.0/driver/razercommon.h` outputs 2.3.0?

**Comment by PDXsailor** [comment]
yes, it shows 2.3.0

**Comment by danielrwilliams** [comment]
Ok, so I tried the nuclear option. Purged (not removed) all *razer* packages and then the PPA, rebooted, and then followed the installation instructions on the OpenRazer site. Still have the same issue.

My version from /sys/bus/hid/drivers/razerkbd/0*/version shows 1.1.6, and razercommon.h shows 2.3.0. I have a BlackWidow Chroma v2 and run KDE Neon (based on Ubuntu 16.04).  The razerkbd module is shown as loaded in lsmod. Until the recent openrazer daemon update, it was working flawlessly on this system.

**Comment by danielrwilliams** [comment]
I have figured it out and have it running fine now on my system. :)

Steps I took to fix:
1. Purged all *razer* and *polychromatic* packages.

2. Remove all versions of the razer*.ko out of /lib/modules. For some reason, I had an an old /lib/modules/[KERNEL_VERSION] directory present w/the razer* modules for a kernel I no longer had installed (shrug).

3. Ran `sudo dpkg-reconfigure linux-image-[KERNEL_VERSION]` to regenerate the initrd.img. So my assumption was when this kernel was installed, it picked up the older module version instead of the newer one for my current kernel. This is what had me pulling my hair out this morning for a couple hours: all razer modules were purged from the filesystem, but yet after a reboot razerkbd would still be loaded.

Thanks lah7 for your help! Your last comment pointed me to the old kernel module directory.

**Comment by PDXsailor** [comment]
That did the trick for me as well. I suppose that the issue shouldn't close until changes are made so that there is no repeat occurrence, but as far as I (OP) am concerned it can be closed.

**Comment by z3ntu** [comment]
The next version will change the version numbes of the dkms module according to the openrazer version number. Hopefully this will mitigate whatever caused this. But honestly I still don't know where the old version of the module was hiding in...

**Comment by PDXsailor** [comment]
I wonder if this only happens to those of us that update the kernel as available. IIRC the default is for kernel updates to not be applied (level 4 or 5) unless all levels are selected. Anyway, if we are at an impasse and we have a fix then shall we close it? If it happens in the future we can open a new ticket...

**Comment by PDXsailor** [comment]
That is funny - I'm runniing 4.15.13.0 on Mint 18.3 (16.04 based), with a single fall-back kernel at 4.14. With a Kaby Lake CPU I don't want a kernel without support.

Thanks for the help.
