### ISSUE TITLE
Daemon Isn't Connecting to Device Manager!

### ISSUE THREAD

**Issue by Cutday** [polychromatic/polychromatic#157]
I have no idea what I am doing wrong. I was trying to install razer drivers for my mouse and headset

Here's my mouse: Razer Deathadder Chroma (Not sure what year cause I bought it off Ebay) - *It's a legit Razer mouse*
Here's my headset: Razer Krakens 7.1 Chroma

Now, here's the entire log when I type openrazer-daemon -Fv
```
2018-05-18 16:56:55 | razer                          | INFO     | Initialising Daemon (v2.3.0). Pid: 1037
2018-05-18 16:56:55 | razer.screensaver              | INFO     | Initialising DBus Screensaver Monitor
2018-05-18 16:56:55 | razer                          | DEBUG    | Loaded device specification: RazerAbyssus ---------------------------- (1532:0042)
2018-05-18 16:56:55 | razer                          | DEBUG    | Loaded device specification: RazerAbyssus1800 ------------------------ (1532:0020)
2018-05-18 16:56:55 | razer                          | DEBUG    | Loaded device specification: RazerAbyssusV2 -------------------------- (1532:005B)
2018-05-18 16:56:55 | razer                          | DEBUG    | Loaded device specification: RazerAnansi ----------------------------- (1532:010F)
2018-05-18 16:56:55 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowChroma ------------------- (1532:0203)
2018-05-18 16:56:55 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowChromaOverwatch ---------- (1532:0211)
2018-05-18 16:56:55 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowChromaTournamentEdition -- (1532:0209)
2018-05-18 16:56:55 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowChromaV2 ----------------- (1532:0221)
2018-05-18 16:56:55 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowClassic ------------------ (1532:011B)
2018-05-18 16:56:55 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowClassicAlternate --------- (1532:010E)
2018-05-18 16:56:55 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowUltimate2012 ------------- (1532:010D)
2018-05-18 16:56:55 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowUltimate2013 ------------- (1532:011A)
2018-05-18 16:56:55 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowUltimate2016 ------------- (1532:0214)
2018-05-18 16:56:55 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowXChroma ------------------ (1532:0216)
2018-05-18 16:56:55 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowXTournamentEditionChroma - (1532:021A)
2018-05-18 16:56:55 | razer                          | DEBUG    | Loaded device specification: RazerBlackWidowXUltimate ---------------- (1532:0217)
2018-05-18 16:56:55 | razer                          | DEBUG    | Loaded device specification: RazerBladeLate2016 ---------------------- (1532:0224)
2018-05-18 16:56:55 | razer                          | DEBUG    | Loaded device specification: RazerBladePro2017 ----------------------- (1532:0225)
2018-05-18 16:56:55 | razer                          | DEBUG    | Loaded device specification: RazerBladePro2017FullHD ----------------- (1532:022F)
2018-05-18 16:56:55 | razer                          | DEBUG    | Loaded device specification: RazerBladeProLate2016 ------------------- (1532:0210)
2018-05-18 16:56:55 | razer                          | DEBUG    | Loaded device specification: RazerBladeQHD --------------------------- (1532:020F)
2018-05-18 16:56:55 | razer                          | DEBUG    | Loaded device specification: RazerBladeStealth ----------------------- (1532:0205)
2018-05-18 16:56:55 | razer                          | DEBUG    | Loaded device specification: RazerBladeStealthLate2016 --------------- (1532:0220)
2018-05-18 16:56:55 | razer                          | DEBUG    | Loaded device specification: RazerBladeStealthLate2017 --------------- (1532:0232)
2018-05-18 16:56:55 | razer                          | DEBUG    | Loaded device specification: RazerBladeStealthMid2017 ---------------- (1532:022D)
2018-05-18 16:56:55 | razer                          | DEBUG    | Loaded device specification: RazerChromaMugHolder -------------------- (1532:0F07)
2018-05-18 16:56:55 | razer                          | DEBUG    | Loaded device specification: RazerCore ------------------------------- (1532:0215)
2018-05-18 16:56:55 | razer                          | DEBUG    | Loaded device specification: RazerDeathAdderChroma ------------------- (1532:0043)
2018-05-18 16:56:55 | razer                          | DEBUG    | Loaded device specification: RazerDeathAdderElite -------------------- (1532:005C)
2018-05-18 16:56:55 | razer                          | DEBUG    | Loaded device specification: RazerDeathStalkerChroma ----------------- (1532:0204)
2018-05-18 16:56:55 | razer                          | DEBUG    | Loaded device specification: RazerDeathStalkerExpert ----------------- (1532:0202)
2018-05-18 16:56:55 | razer                          | DEBUG    | Loaded device specification: RazerDiamondbackChroma ------------------ (1532:004C)
2018-05-18 16:56:55 | razer                          | DEBUG    | Loaded device specification: RazerFirefly ---------------------------- (1532:0C00)
2018-05-18 16:56:55 | razer                          | DEBUG    | Loaded device specification: RazerImperator -------------------------- (1532:002F)
2018-05-18 16:56:55 | razer                          | DEBUG    | Loaded device specification: RazerKraken ----------------------------- (1532:0504)
2018-05-18 16:56:55 | razer                          | DEBUG    | Loaded device specification: RazerKrakenClassic ---------------------- (1532:0501)
2018-05-18 16:56:55 | razer                          | DEBUG    | Loaded device specification: RazerKrakenV2 --------------------------- (1532:0510)
2018-05-18 16:56:55 | razer                          | DEBUG    | Loaded device specification: RazerMamba2012Wired --------------------- (1532:0024)
2018-05-18 16:56:55 | razer                          | DEBUG    | Loaded device specification: RazerMamba2012Wireless ------------------ (1532:0025)
2018-05-18 16:56:55 | razer                          | DEBUG    | Loaded device specification: RazerMambaChromaWired ------------------- (1532:0044)
2018-05-18 16:56:55 | razer                          | DEBUG    | Loaded device specification: RazerMambaChromaWireless ---------------- (1532:0045)
2018-05-18 16:56:55 | razer                          | DEBUG    | Loaded device specification: RazerMambaTE ---------------------------- (1532:0046)
2018-05-18 16:56:55 | razer                          | DEBUG    | Loaded device specification: RazerNaga2014 --------------------------- (1532:0040)
2018-05-18 16:56:55 | razer                          | DEBUG    | Loaded device specification: RazerNagaChroma ------------------------- (1532:0053)
2018-05-18 16:56:55 | razer                          | DEBUG    | Loaded device specification: RazerNagaHex ---------------------------- (1532:0041)
2018-05-18 16:56:55 | razer                          | DEBUG    | Loaded device specification: RazerNagaHexRed ------------------------- (1532:0036)
2018-05-18 16:56:55 | razer                          | DEBUG    | Loaded device specification: RazerNagaHexV2 -------------------------- (1532:0050)
2018-05-18 16:56:55 | razer                          | DEBUG    | Loaded device specification: RazerNostromo --------------------------- (1532:0111)
2018-05-18 16:56:55 | razer                          | DEBUG    | Loaded device specification: RazerOrbweaver -------------------------- (1532:0113)
2018-05-18 16:56:55 | razer                          | DEBUG    | Loaded device specification: RazerOrbweaverChroma -------------------- (1532:0207)
2018-05-18 16:56:55 | razer                          | DEBUG    | Loaded device specification: RazerOrnata ----------------------------- (1532:021F)
2018-05-18 16:56:55 | razer                          | DEBUG    | Loaded device specification: RazerOrnataChroma ----------------------- (1532:021E)
2018-05-18 16:56:55 | razer                          | DEBUG    | Loaded device specification: RazerOrochi2011 ------------------------- (1532:0013)
2018-05-18 16:56:55 | razer                          | DEBUG    | Loaded device specification: RazerOrochi2013 ------------------------- (1532:0039)
2018-05-18 16:56:55 | razer                          | DEBUG    | Loaded device specification: RazerOrochiWired ------------------------ (1532:0048)
2018-05-18 16:56:55 | razer                          | DEBUG    | Loaded device specification: RazerOuroboros -------------------------- (1532:0032)
2018-05-18 16:56:55 | razer                          | DEBUG    | Loaded device specification: RazerTaipan ----------------------------- (1532:0034)
2018-05-18 16:56:55 | razer                          | DEBUG    | Loaded device specification: RazerTartarus --------------------------- (1532:0201)
2018-05-18 16:56:55 | razer                          | DEBUG    | Loaded device specification: RazerTartarusChroma --------------------- (1532:0208)
2018-05-18 16:56:55 | razer                          | INFO     | Found device.0: 0003:1532:0504.0003
2018-05-18 16:56:55 | razer.device0                  | INFO     | Initialising device.0 RazerKraken
2018-05-18 16:56:55 | razer.device0                  | DEBUG    | Adding razer.device.misc.getVidPid method to DBus
2018-05-18 16:56:55 | razer.device0                  | DEBUG    | Adding razer.device.misc.getRazerUrls method to DBus
2018-05-18 16:56:55 | razer.device0                  | DEBUG    | Adding razer.device.misc.getSerial method to DBus
2018-05-18 16:56:55 | razer.device0                  | DEBUG    | Adding razer.device.misc.resumeDevice method to DBus
2018-05-18 16:56:55 | razer.device0                  | DEBUG    | Adding razer.device.misc.getDriverVersion method to DBus
2018-05-18 16:56:55 | razer.device0                  | DEBUG    | Adding razer.device.misc.setDeviceMode method to DBus
2018-05-18 16:56:55 | razer.device0                  | DEBUG    | Adding razer.device.misc.getDeviceMode method to DBus
2018-05-18 16:56:55 | razer.device0                  | DEBUG    | Adding razer.device.misc.suspendDevice method to DBus
2018-05-18 16:56:55 | razer.device0                  | DEBUG    | Adding razer.device.misc.hasDedicatedMacroKeys method to DBus
2018-05-18 16:56:55 | razer.device0                  | DEBUG    | Adding razer.device.misc.getFirmware method to DBus
2018-05-18 16:56:55 | razer.device0                  | DEBUG    | Adding razer.device.misc.getMatrixDimensions method to DBus
2018-05-18 16:56:55 | razer.device0                  | DEBUG    | Adding razer.device.misc.hasMatrix method to DBus
2018-05-18 16:56:55 | razer.device0                  | DEBUG    | Adding razer.device.misc.getDeviceName method to DBus
2018-05-18 16:56:55 | razer.device0                  | DEBUG    | Adding razer.device.misc.getDeviceType method to DBus
2018-05-18 16:56:55 | razer.device0                  | DEBUG    | Adding razer.device.lighting.chroma.setStatic method to DBus
2018-05-18 16:56:55 | razer.device0                  | DEBUG    | Adding razer.device.lighting.chroma.setSpectrum method to DBus
2018-05-18 16:56:55 | razer.device0                  | DEBUG    | Adding razer.device.lighting.chroma.setNone method to DBus
2018-05-18 16:56:55 | razer.device0                  | DEBUG    | Adding razer.device.lighting.chroma.setBreathSingle method to DBus
2018-05-18 16:56:55 | razer.device0                  | DEBUG    | Adding razer.device.lighting.kraken.getCurrentEffect method to DBus
2018-05-18 16:56:55 | razer.device0                  | DEBUG    | Adding razer.device.lighting.kraken.getStaticArgs method to DBus
2018-05-18 16:56:55 | razer.device0                  | DEBUG    | Adding razer.device.lighting.kraken.getBreathArgs method to DBus
2018-05-18 16:56:55 | razer.device0                  | DEBUG    | Adding razer.device.lighting.kraken.setCustom method to DBus
2018-05-18 16:56:55 | razer                          | INFO     | Found device.1: 0003:1532:0043.0004
2018-05-18 16:56:55 | razer.device1                  | INFO     | Initialising device.1 RazerDeathAdderChroma
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/daemonize.py", line 245, in start
    self.action(*privileged_action_result)
  File "/usr/bin/openrazer-daemon", line 125, in run_daemon
    test_dir=args.test_dir)
  File "/usr/lib/python3/dist-packages/openrazer_daemon/daemon.py", line 106, in __init__
    self._load_devices(first_run=True)
  File "/usr/lib/python3/dist-packages/openrazer_daemon/daemon.py", line 400, in _load_devices
    razer_device = device_class(sys_path, device_number, self._config, testing=self._test_dir is not None, additional_interfaces=sorted(additional_interfaces))
  File "/usr/lib/python3/dist-packages/openrazer_daemon/hardware/mouse.py", line 249, in __init__
    super(RazerDeathAdderChroma, self).__init__(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/openrazer_daemon/hardware/device_base.py", line 441, in __init__
    super().__init__(device_path, device_number, config, testing, additional_interfaces, additional_methods)
  File "/usr/lib/python3/dist-packages/openrazer_daemon/hardware/device_base.py", line 64, in __init__
    self.serial = self.get_serial()
  File "/usr/lib/python3/dist-packages/openrazer_daemon/hardware/device_base.py", line 208, in get_serial
    serial = f.read().strip()
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/openrazer_daemon/hardware/device_base.py", line 427, in __del__
    self.close()
  File "/usr/lib/python3/dist-packages/openrazer_daemon/hardware/device_base.py", line 340, in close
    if not self._is_closed:
AttributeError: 'RazerDeathAdderChroma' object has no attribute '_is_closed'
Stopping daemon.
```
If you know the problem, state the fix for it very specifically! I am awful at using Ubuntu, and I'm still learning so I need to know exactly what I am doing! Thank you!!!!

**Comment by lah7** [comment]
Hi, as this a problem at a driver/daemon level, [please raise the issue on the OpenRazer repository](https://github.com/openrazer/openrazer/issues). Those guys are more knowledgeable with this sort of problem and will be able to assist / fix this.

Once the driver/daemon problem is resolved, Polychromatic will start functioning. Good luck!
