### ISSUE TITLE
Keyboard is not shown when setting up new Application Profile.

### ISSUE THREAD

**Issue by Devrim-Celik** [polychromatic/polychromatic#217]
Hey, 

just installed polychromatic on my Razer Blade Stealth (2019) with Ubuntu 18.04. It generally works, I can use all default lighting effect, but when I try to design my own, it seems that the keyboard is missing:

![Screenshot from 2019-11-03 14-50-23](https://user-images.githubusercontent.com/16657035/68086207-5a25b880-fe49-11e9-906d-5c3d01da07bd.png)

**Comment by lah7** [comment]
Hi! Likely an exception was thrown which prevented the graphic from loading. Please try running via the Terminal and let me know what it says:

    polychromatic-controller -v

This v0.3.12 version is getting _really old_, but the new developments are not stable yet. In the meantime, you may need to patch the graphic so all the keys work for your Blade Stealth:

    wget https://raw.githubusercontent.com/polychromatic/polychromatic/8607f48d6776ec3d3c84150b7b2506775590b890/data/img/blackwidow-chroma-keyboard-layout.svg
    sudo mv blackwidow-chroma-keyboard-layout.svg /usr/share/polychromatic/mapping/


(From https://github.com/openrazer/openrazer/issues/824#issuecomment-495947506)

**Comment by Devrim-Celik** [comment]
Output of  ```polychromatic-controller  -v```:
```
Verbose enabled
Set scale to: 1.0
Initialised Window.
Version 0.3.12-stable
Loading daemon...
Gathering devices...
 -- Found: Razer Blade Stealth (2019)
Loading application profiles...

Set active device: Razer Blade Stealth (2019)
Device supports 'brightness'
```

I tried the patch, still does not work :/

**Comment by lah7** [comment]
The patch amends the keyboard graphic so it only shows the keys available for the laptop, :paintbrush:  but before we see those results, we need to find out why the graphic isn't appearing at all.

I was hoping for a stack trace, please could you try:

    polychromatic-controller -d

And proceed to create a new "application profile" and paste after entering the editor.

:bulb: If you happened to have used a newer dev version, try deleting `~/.config/polychromatic`.

Equally, since Polychromatic relies on OpenRazer to state the capabilities, please post the output of this to double check:

    python3 -c "import openrazer.client;print(openrazer.client.DeviceManager().devices[0].capabilities)"

**Comment by Devrim-Celik** [comment]
Sure. Output of ```python3 -c "import openrazer.client;print(openrazer.client.DeviceManager().devices[0].capabilities)":

```
{'name': True, 'type': True, 'firmware_version': True, 'serial': True, 'brightness': True, 'macro_logic': False, 'keyboard_layout': True, 'lighting': True, 'lighting_breath_single': True, 'lighting_breath_dual': False, 'lighting_breath_triple': False, 'lighting_breath_random': True, 'lighting_wave': False, 'lighting_reactive': False, 'lighting_none': True, 'lighting_spectrum': True, 'lighting_static': True, 'lighting_starlight_single': False, 'lighting_starlight_dual': False, 'lighting_starlight_random': False, 'lighting_ripple': False, 'lighting_ripple_random': False, 'lighting_pulsate': False, 'lighting_led_matrix': True, 'lighting_led_single': False, 'lighting_logo': False, 'lighting_logo_active': False, 'lighting_logo_blinking': False, 'lighting_logo_brightness': False, 'lighting_logo_pulsate': False, 'lighting_logo_spectrum': False, 'lighting_logo_static': False, 'lighting_logo_none': False, 'lighting_logo_reactive': False, 'lighting_logo_wave': False, 'lighting_logo_breath_single': False, 'lighting_logo_breath_dual': False, 'lighting_logo_breath_random': False, 'lighting_scroll': False, 'lighting_scroll_active': False, 'lighting_scroll_blinking': False, 'lighting_scroll_brightness': False, 'lighting_scroll_pulsate': False, 'lighting_scroll_spectrum': False, 'lighting_scroll_static': False, 'lighting_scroll_none': False, 'lighting_scroll_reactive': False, 'lighting_scroll_wave': False, 'lighting_scroll_breath_single': False, 'lighting_scroll_breath_dual': False, 'lighting_scroll_breath_random': False, 'lighting_left': False, 'lighting_left_active': False, 'lighting_left_brightness': False, 'lighting_left_spectrum': False, 'lighting_left_static': False, 'lighting_left_none': False, 'lighting_left_reactive': False, 'lighting_left_wave': False, 'lighting_left_breath_single': False, 'lighting_left_breath_dual': False, 'lighting_left_breath_random': False, 'lighting_right': False, 'lighting_right_active': False, 'lighting_right_brightness': False, 'lighting_right_spectrum': False, 'lighting_right_static': False, 'lighting_right_none': False, 'lighting_right_reactive': False, 'lighting_right_wave': False, 'lighting_right_breath_single': False, 'lighting_right_breath_dual': False, 'lighting_right_breath_random': False, 'lighting_backlight': False, 'lighting_backlight_active': False, 'game_mode_led': False, 'macro_mode_led': False, 'macro_mode_led_effect': False, 'macro_mode_modifier': False}
```
Output of ```polychromatic-controller -d``` while creating a new application profile (leaving out ```JS``` messages):
```
ERROR:dbus.connection:Unable to set arguments (b'\x00\x00\x0f\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x0f\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x0f\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x03\x00\x0f\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x04\x00\x0f\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x05\x00\x0f\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00',) according to signature None: <class 'ValueError'>: embedded null byte
Traceback (most recent call last):
  File "/usr/bin/polychromatic-controller", line 219, in load_changed_cb
    app.page_loaded()
  File "/usr/bin/polychromatic-controller", line 536, in page_loaded
    page_bindings[self.current_page](self)
  File "/usr/bin/polychromatic-controller", line 2566, in profile_editor
    appobj.profiles.send_profile_to_keyboard(appobj.active_device, profile_data)
  File "/usr/lib/python3/dist-packages/polychromatic/profiles.py", line 151, in send_profile_to_keyboard
    kbd_obj.fx.advanced.draw()
  File "/usr/lib/python3/dist-packages/openrazer/client/fx.py", line 600, in draw
    self._draw(bytes(self.matrix))
  File "/usr/lib/python3/dist-packages/openrazer/client/fx.py", line 592, in _draw
    self._lighting_dbus.setKeyRow(ba)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 641, in call_blocking
    message.append(signature=signature, *args)
ValueError: embedded null byte
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 109, in apport_excepthook
    pr.add_proc_info(extraenv=['PYTHONPATH', 'PYTHONHOME'])
  File "/usr/lib/python3/dist-packages/apport/report.py", line 543, in add_proc_info
    self.add_proc_environ(pid, extraenv)
  File "/usr/lib/python3/dist-packages/apport/report.py", line 610, in add_proc_environ
    env = _read_file('environ', dir_fd=proc_pid_fd).replace('\n', '\\n')
  File "/usr/lib/python3/dist-packages/apport/report.py", line 73, in _read_file
    with open(path, 'rb', opener=lambda path, mode: os.open(path, mode, dir_fd=dir_fd)) as fd:
  File "/usr/lib/python3/dist-packages/apport/report.py", line 73, in <lambda>
    with open(path, 'rb', opener=lambda path, mode: os.open(path, mode, dir_fd=dir_fd)) as fd:
TypeError: argument should be integer or None, not list

Original exception was:
Traceback (most recent call last):
  File "/usr/bin/polychromatic-controller", line 219, in load_changed_cb
    app.page_loaded()
  File "/usr/bin/polychromatic-controller", line 536, in page_loaded
    page_bindings[self.current_page](self)
  File "/usr/bin/polychromatic-controller", line 2566, in profile_editor
    appobj.profiles.send_profile_to_keyboard(appobj.active_device, profile_data)
  File "/usr/lib/python3/dist-packages/polychromatic/profiles.py", line 151, in send_profile_to_keyboard
    kbd_obj.fx.advanced.draw()
  File "/usr/lib/python3/dist-packages/openrazer/client/fx.py", line 600, in draw
    self._draw(bytes(self.matrix))
  File "/usr/lib/python3/dist-packages/openrazer/client/fx.py", line 592, in _draw
    self._lighting_dbus.setKeyRow(ba)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 641, in call_blocking
    message.append(signature=signature, *args)
ValueError: embedded null byte
** Command: profile-save
Saving profile UUID: 1572873941160085
ERROR:dbus.connection:Unable to set arguments (b'\x00\x00\x0f\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x0f\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x0f\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x03\x00\x0f\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x04\x00\x0f\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x05\x00\x0f\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00',) according to signature None: <class 'ValueError'>: embedded null byte
Traceback (most recent call last):
  File "/usr/bin/polychromatic-controller", line 205, in title_changed_cb
    app.process_command(title)
  File "/usr/bin/polychromatic-controller", line 995, in process_command
    self.profiles.send_profile_to_keyboard(self.active_device, self.profiles.memory)
  File "/usr/lib/python3/dist-packages/polychromatic/profiles.py", line 151, in send_profile_to_keyboard
    kbd_obj.fx.advanced.draw()
  File "/usr/lib/python3/dist-packages/openrazer/client/fx.py", line 600, in draw
    self._draw(bytes(self.matrix))
  File "/usr/lib/python3/dist-packages/openrazer/client/fx.py", line 592, in _draw
    self._lighting_dbus.setKeyRow(ba)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 641, in call_blocking
    message.append(signature=signature, *args)
ValueError: embedded null byte
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 109, in apport_excepthook
    pr.add_proc_info(extraenv=['PYTHONPATH', 'PYTHONHOME'])
  File "/usr/lib/python3/dist-packages/apport/report.py", line 543, in add_proc_info
    self.add_proc_environ(pid, extraenv)
  File "/usr/lib/python3/dist-packages/apport/report.py", line 610, in add_proc_environ
    env = _read_file('environ', dir_fd=proc_pid_fd).replace('\n', '\\n')
  File "/usr/lib/python3/dist-packages/apport/report.py", line 73, in _read_file
    with open(path, 'rb', opener=lambda path, mode: os.open(path, mode, dir_fd=dir_fd)) as fd:
  File "/usr/lib/python3/dist-packages/apport/report.py", line 73, in <lambda>
    with open(path, 'rb', opener=lambda path, mode: os.open(path, mode, dir_fd=dir_fd)) as fd:
TypeError: argument should be integer or None, not list

Original exception was:
Traceback (most recent call last):
  File "/usr/bin/polychromatic-controller", line 205, in title_changed_cb
    app.process_command(title)
  File "/usr/bin/polychromatic-controller", line 995, in process_command
    self.profiles.send_profile_to_keyboard(self.active_device, self.profiles.memory)
  File "/usr/lib/python3/dist-packages/polychromatic/profiles.py", line 151, in send_profile_to_keyboard
    kbd_obj.fx.advanced.draw()
  File "/usr/lib/python3/dist-packages/openrazer/client/fx.py", line 600, in draw
    self._draw(bytes(self.matrix))
  File "/usr/lib/python3/dist-packages/openrazer/client/fx.py", line 592, in _draw
    self._lighting_dbus.setKeyRow(ba)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 641, in call_blocking
    message.append(signature=signature, *args)
ValueError: embedded null byte
```

**Comment by lah7** [comment]
Thanks. It looks like an issue with the driver (OpenRazer) or DBUS. The exception is being thrown when the application tells the daemon to render the custom frame on your keyboard.

So, to make the graphic to appear, _a workaround_ may be to turn off "Enable live switching", "Enable live preview" and "Always activate profiles after saving" in :wrench: (Preferences) → **General** Tab.

![image](https://user-images.githubusercontent.com/13032135/68125533-b94b0200-ff09-11e9-9e2e-9d0e9a727098.png)

But this is only masking the issue - as the underlying cause is OpenRazer being unable to send custom frames to the hardware. I'd suggest [raising the issue in OpenRazer's repository](https://github.com/openrazer/openrazer/issues) (be sure to mention the firmware version) as it's outside of Polychromatic.

You should be able to replicate the error by running this Python script (.py) - it would normally light up the first key (ESC):

```python
#!/usr/bin/python3
import openrazer.client
a = openrazer.client.DeviceManager().devices[0]
a.fx.advanced.matrix[0,0] = [0,255,0]
a.fx.advanced.draw()
```
