### ISSUE TITLE
No module named 'pylib'

### ISSUE THREAD

**Issue by p5ych0** [polychromatic/polychromatic#232]
```
[~]$ polychromatic-controller
Traceback (most recent call last):
File "/usr/bin/polychromatic-controller", line 52, in <module>
import pylib.preferences as pref
ModuleNotFoundError: No module named 'pylib'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/bin/polychromatic-controller", line 58, in <module>
import polychromatic.preferences as pref
ModuleNotFoundError: No module named 'polychromatic'
[~]$ PYTHONPATH=/usr/lib/python3.7/site-packages polychromatic-controller
Traceback (most recent call last):
File "/usr/bin/polychromatic-controller", line 52, in <module>
import pylib.preferences as pref
ModuleNotFoundError: No module named 'pylib'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/bin/polychromatic-controller", line 58, in <module>
import polychromatic.preferences as pref
ModuleNotFoundError: No module named 'polychromatic'
```
Can't make it running on Fedora 31
any ideas?

**Comment by lah7** [comment]
I'm guessing this was installed with the [Fedora package?](https://polychromatic.app/download/fedora/) It certainly looks like the Python modules can't be found. What's the output of this command?

    python -c "import sys; print('\n'.join(sys.path))"

The files should be at `/usr/lib/python3.7/site-packages/polychromatic` unless your `PYTHONPATH` or version of Python is different to the default. Fedora 31 still ships Python 3.7.

`pylib` is only used when running from a clone of this repository, e.g.
```
git clone https://github.com/polychromatic/polychromatic.git
cd polychromatic
./polychromatic-controller
```

**Comment by p5ych0** [comment]
my fault, installed package from rawhide which supposed to use p3.8
