### ISSUE TITLE
TypeError on app launch

### ISSUE THREAD

**Issue by tomers** [polychromatic/polychromatic#251]
An error is shown immediately when starting the app:
```
$ polychromatic-controller 
/usr/bin/polychromatic-controller:290: DeprecationWarning: Gtk.Window.set_wmclass is deprecated
  self.window.set_wmclass("polychromatic-controller", "polychromatic-controller")
/usr/bin/polychromatic-controller:292: DeprecationWarning: Gtk.Widget.modify_bg is deprecated
  self.window.modify_bg(Gtk.StateType(0), Gdk.Color(0, 0, 0))
Traceback (most recent call last):
  File "/usr/bin/polychromatic-controller", line 219, in load_changed_cb
    app.page_loaded()
  File "/usr/bin/polychromatic-controller", line 536, in page_loaded
    page_bindings[self.current_page](self)
  File "/usr/bin/polychromatic-controller", line 2191, in menu
    "/etc/apt/sources.list.d/lah7-ubuntu-polychromatic-" + codename + ".list",
TypeError: can only concatenate str (not "function") to str
```

**Comment by lah7** [comment]
Which distro?

If you're using Ubuntu 20.04, there is a package update coming as we speak to resolve this issue.

**Comment by tomers** [comment]
This should solve it:
```
$ git diff polychromatic-controller
diff --git a/polychromatic-controller b/polychromatic-controller
index c8694c9..40c11a6 100755
--- a/polychromatic-controller
+++ b/polychromatic-controller
@@ -2187,6 +2187,8 @@ class PageLoaded():
         distro_name = distro.linux_distribution()[0]
         if distro_name == "Ubuntu" or distro_name == "Debian":
             codename = distro.codename
+            if callable(codename):
+                codename = codename()
             for source_file in [
                 "/etc/apt/sources.list.d/lah7-ubuntu-polychromatic-" + codename + ".list",
                 "/etc/apt/sources.list.d/lah7-ubuntu-polychromatic-daily-" + codename + ".list"
```

**Comment by lah7** [comment]
An updated package (`0.3.12-focal6`) has been published that fixes this problem. (Same as #250)
