### ISSUE TITLE
Polychromatic application not loading

### ISSUE THREAD

**Issue by kaykhancheckpoint** [polychromatic/polychromatic#293]
Hi i have followed the installation instructions here https://github.com/polychromatic/polychromatic#-openrazer

i can see two polychromatic applications. 
![image](https://user-images.githubusercontent.com/65535942/96572616-f8ae6200-12c4-11eb-8b36-8d9568d226a7.png)

However clicking on them does not load the application. I have tried removing and reinstalling polychromatic with no avail. Can anyone help me debug this problem.

Ubuntu: 20.04

**Comment by lah7** [comment]
Please run the application via the Terminal, this should output some handy details.

    polychromatic-controller -v
    polychromatic-tray-applet -v

**Comment by kaykhancheckpoint** [comment]
@lah7 

When i run those commands i get the following errors:

```
polychromatic-controller -v
Traceback (most recent call last):
  File "/usr/bin/polychromatic-controller", line 26, in <module>
    import distro
```


```
polychromatic-tray-applet -v
Traceback (most recent call last):
  File "/usr/bin/polychromatic-tray-applet", line 21, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'

```

**Comment by lah7** [comment]
Sounds like a local installation of Python could be interfering. Try changing the shebang of the files:

    sudo sed -i 's^#!/usr/bin/env python3^#!/usr/bin/python3^g' /usr/bin/polychromatic-controller
    sudo sed -i 's^#!/usr/bin/env python3^#!/usr/bin/python3^g' /usr/bin/polychromatic-tray-applet

This will change the first line ("the shebang") of each file from `#/usr/bin/env python3` to `#!/usr/bin/python3`, so it points to the system's packaged versions of Python, then try launching again. :crossed_fingers: 

You'll only need to do this once, since the latter is used in future versions.

---

If the `ModuleNotFoundError` for `import distro` appears again, then you may need to explicitly install that package:

    sudo apt install python3-distro

**Comment by kaykhancheckpoint** [comment]
Updating the shebang worked.

thank you for your help.

**Comment by Jossome** [comment]
Hi, I fixed the error caused by shebang, but another error pumped out:
```
** (polychromatic-controller:3537): WARNING **: Failed to load shared library 'libgtk-3.so.0' referenced by the typelib: /usr/lib/x86_64-linux-gnu/libatk-1.0.so.0: undefined symbol: g_log_structured_standard

** (polychromatic-controller:3537): WARNING **: Failed to load shared library 'libatk-1.0.so.0' referenced by the typelib: /usr/lib/x86_64-linux-gnu/libatk-1.0.so.0: undefined symbol: g_log_structured_standard
Traceback (most recent call last):
  File "/usr/bin/polychromatic-controller", line 72, in <module>
    from gi.repository import GLib, Gtk, Gdk, WebKit2
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/usr/lib/python3/dist-packages/gi/importer.py", line 146, in load_module
    dynamic_module = load_overrides(introspection_module)
  File "/usr/lib/python3/dist-packages/gi/overrides/__init__.py", line 125, in load_overrides
    override_mod = importlib.import_module(override_package_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 118, in <module>
    class Widget(Gtk.Widget):
  File "/usr/lib/python3/dist-packages/gi/module.py", line 181, in __getattr__
    interfaces = tuple(interface for interface in get_interfaces_for_object(info)
  File "/usr/lib/python3/dist-packages/gi/module.py", line 105, in get_interfaces_for_object
    interfaces.append(getattr(module, name))
  File "/usr/lib/python3/dist-packages/gi/module.py", line 220, in __getattr__
    wrapper = metaclass(name, bases, dict_)
  File "/usr/lib/python3/dist-packages/gi/types.py", line 234, in __init__
    register_interface_info(cls.__info__.get_g_type())
TypeError: must be an interface
```

I'm using Ubuntu 18.04

**Comment by lah7** [comment]
@Jossome It looks like something is up with GTK / ATK on your system judging from the first two warnings.

All I can suggest is reinstalling those libraries.

    sudo apt install --reinstall python3-gi gir1.2-gtk-3.0 gir1.2-atk-1.0 libatk-adaptor libatk-bridge2.0-0 libatk1.0-0 libatk1.0-data libatkmm-1.5-1v5 libgtk-3-0 libgtk-3-bin libgtk-3-common

I used **Synaptic Package Manager** to figure out which packages may provide this.
