### ISSUE TITLE
Changing Color produces an crash.

### ISSUE THREAD

**Issue by LinuxDonald** [polychromatic/polychromatic#309]
```
$ polychromatic-controller -v
Loading preferences...
Initalising application...
Getting device list...
[openrazer] Initalising Device Manager...
Opening tab: 0
[openrazer] Persistence read unnecessary for Razer Basilisk V2 (Zone: main)
[openrazer] Persistence read unnecessary for Razer Basilisk V2 (Zone: main)
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/polychromatic/controller/shared.py", line 543, in _clicked_change_colour
    picker = ColourPicker(self.appdata, callback_fn, callback_data, btn.current_hex, title, monoscale, preview)
  File "/usr/lib/python3.9/site-packages/polychromatic/controller/shared.py", line 724, in __init__
    self._build_saved_colour_list()
  File "/usr/lib/python3.9/site-packages/polychromatic/controller/shared.py", line 882, in _build_saved_colour_list
    item = self._add_to_tree(colour["name"], colour["hex"])
TypeError: string indices must be integers
Abgebrochen (Speicherabzug geschrieben)
```

**Comment by lah7** [comment]
What is the output of your `colours.json`?

    cat ~/.config/polychromatic/colours.json

Which version have you previously used? (v0.3.12, v0.4.0, v0.5.0). A possible solution is to delete the `colours.json` file and let it regenerate.

**Comment by LinuxDonald** [comment]
Deleting colours.json worked thx :) im using git version. I dont remeber if i used 0.6.0 before it.
