### ISSUE TITLE
polychromatic-tray-applet not showing at Xfce 4.14 (Ubuntu 20.04.3 LTS) 

### ISSUE THREAD

**Issue by tk421** [polychromatic/polychromatic#399]
### Details about the problem

This used to work a few days ago, so this issue is likely to have been introduced in one of the latest updated. 

When log in the desktop, I expect to see an icon in in my desktop in which I can see, access and configure my Razor Devices. 

Right now, this is happening no more - no icon is visible in Xfce.

```
~ polychromatic-tray-applet -v
Verbose enabled
[openrazer] Initalising Device Manager...
Initializing AppIndicator
Initialized AppIndicator
Loading device data...
[openrazer] Persistence read unnecessary for Razer DeathAdder V2 Pro (Wired) (Zone: main)
[openrazer] Persistence read unnecessary for Razer DeathAdder V2 Pro (Wired) (Zone: main)
[openrazer] Could not read get_idle_time. Ignoring.
[openrazer] org.freedesktop.DBus.Error.UnknownMethod: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 658, in _message_cb
    (candidate_method, parent_method) = _method_lookup(self, method_name, interface_name)
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 248, in _method_lookup
    raise UnknownMethodException('%s is not a valid method of interface %s' % (method_name, dbus_interface))
dbus.exceptions.UnknownMethodException: org.freedesktop.DBus.Error.UnknownMethod: Unknown method: getIdleTime is not a valid method of interface razer.device.power

[openrazer] Could not read get_low_battery_threshold. Ignoring.
[openrazer] org.freedesktop.DBus.Error.UnknownMethod: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 658, in _message_cb
    (candidate_method, parent_method) = _method_lookup(self, method_name, interface_name)
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 248, in _method_lookup
    raise UnknownMethodException('%s is not a valid method of interface %s' % (method_name, dbus_interface))
dbus.exceptions.UnknownMethodException: org.freedesktop.DBus.Error.UnknownMethod: Unknown method: getLowBatteryThreshold is not a valid method of interface razer.device.power

[openrazer] Could not read get_idle_time. Ignoring.
[openrazer] org.freedesktop.DBus.Error.UnknownMethod: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 658, in _message_cb
    (candidate_method, parent_method) = _method_lookup(self, method_name, interface_name)
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 248, in _method_lookup
    raise UnknownMethodException('%s is not a valid method of interface %s' % (method_name, dbus_interface))
dbus.exceptions.UnknownMethodException: org.freedesktop.DBus.Error.UnknownMethod: Unknown method: getIdleTime is not a valid method of interface razer.device.power

[openrazer] Could not read get_low_battery_threshold. Ignoring.
[openrazer] org.freedesktop.DBus.Error.UnknownMethod: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 658, in _message_cb
    (candidate_method, parent_method) = _method_lookup(self, method_name, interface_name)
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 248, in _method_lookup
    raise UnknownMethodException('%s is not a valid method of interface %s' % (method_name, dbus_interface))
dbus.exceptions.UnknownMethodException: org.freedesktop.DBus.Error.UnknownMethod: Unknown method: getLowBatteryThreshold is not a valid method of interface razer.device.power

Creating menus...
/usr/bin/polychromatic-tray-applet:200: DeprecationWarning: Gtk.ImageMenuItem.set_image is deprecated
  item.set_image(img)            # GTK3: Deprecated, no replacement!
- Razer BlackWidow V3 Pro (Wired)
- Razer DeathAdder V2 Pro (Wired)
Finished setting up applet.

```

The icon is not visible in Xfce. 

### Operating System / Desktop Environment / Version(s)

Xfce 4.14 
Ubuntu 20.04.3 LTS

```
~ dpkg -l | grep polychroma
ii  polychromatic                         0.6.0-216~g1cef755~focal              all          RGB lighting utility (metapackage)
ii  polychromatic-cli                     0.6.0-216~g1cef755~focal              all          RGB lighting utility (CLI interface)
ii  polychromatic-common                  0.6.0-216~g1cef755~focal              all          RGB lighting utility (common files)
ii  polychromatic-controller              0.6.0-216~g1cef755~focal              all          RGB lighting utility (Qt interface)
ii  polychromatic-tray-applet             0.6.0-216~g1cef755~focal              all          RGB lighting utility (GTK-based AppIndicator)
```

```
~ dpkg -l | grep razer     
ii  openrazer-daemon                      3.2.0~ubuntu20.04.1                   all          OpenRazer peripheral drivers (daemon)
ii  openrazer-driver-dkms                 3.2.0~ubuntu20.04.1                   all          OpenRazer peripheral drivers (DKMS)
ii  openrazer-meta                        3.2.0~ubuntu20.04.1                   all          OpenRazer peripheral drivers (metapackage)
ii  python3-openrazer                     3.2.0~ubuntu20.04.1                   all          OpenRazer peripheral drivers (Python 3)
```

**Comment by tk421** [comment]
Invalidating, the icon has simply changed.
