### ISSUE TITLE
Tray applet crashes at startup on Archlinux

### ISSUE THREAD

**Issue by Iglu47** [polychromatic/polychromatic#483]
### Details about the problem

Tray applet crashes at startup with following output:
```Python traceback
Traceback (most recent call last):
  File "/usr/bin/polychromatic-tray-applet", line 868, in <module>
    app.start()
  File "/usr/bin/polychromatic-tray-applet", line 276, in start
    self.build_indicator()
  File "/usr/bin/polychromatic-tray-applet", line 360, in build_indicator
    self.create_bulk_menu(bulk_menu)
  File "/usr/bin/polychromatic-tray-applet", line 577, in create_bulk_menu
    bulk_options = bulkapply.BulkApplyOptions(self.middleman)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/polychromatic/bulkapply.py", line 80, in __init__
    self.refresh()
  File "/usr/lib/python3.11/site-packages/polychromatic/bulkapply.py", line 102, in refresh
    self._populate_bulk_colours(has_colours)
                                ^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'has_colours' where it is not associated with a value

(polychromatic-tray-applet:2029): Gtk-CRITICAL **: 11:15:05.699: gtk_main_quit: assertion 'main_loops != NULL' failed
```

Following patch works for me as a workaround:
```patch
diff --git a/polychromatic/bulkapply.py b/polychromatic/bulkapply.py
index 96d8226..f1d898f 100644
--- a/polychromatic/bulkapply.py
+++ b/polychromatic/bulkapply.py
@@ -85,6 +85,7 @@ class BulkApplyOptions(object):
         """
         brightness = []
         effects = []
+        has_colours = False
 
         for device in self.devices:
             for zone in device.zones:
```

### Operating System / Desktop Environment / Version(s)

- Archlinux
- Cinnamon 5.8.2
- Python 3.11.3
- OpenRazer 3.6.1
- Polychromatic v0.8.1

### Affected Devices

- Razer BlackWidow Ultimate 2013
- Razer Taipan

**Comment by lah7** [comment]
Thank you! That is the correct fix. It seems we haven't tested 2 non-RGB devices on their own that triggers this crash.
